In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("custdata.tsv", sep="\t")

In [3]:
df.head()

,custid,sex,is.employed,income,marital.stat,health.ins,housing.type,recent.move,num.vehicles,age,state.of.res
0,2068,F,NaN,11300,Married,True,Homeowner free and clear,False,2.0,49.0,Michigan
1,2073,F,NaN,0,Married,True,Rented,True,3.0,40.0,Florida
2,2848,M,True,4500,Never Married,False,Rented,True,3.0,22.0,Georgia
3,5641,M,True,20000,Never Married,False,Occupied with no rent,False,0.0,22.0,New Mexico
4,6369,F,True,12000,Never Married,True,Rented,True,1.0,31.0,Florida

In [4]:
df[["age", "income", "num.vehicles"]].head()

    age  income  num.vehicles
0  49.0   11300           2.0
1  40.0       0           3.0
2  22.0    4500           3.0
3  22.0   20000           0.0
4  31.0   12000           1.0

In [5]:
before_corr = df[["age", "income", "num.vehicles"]].corr()

before_corr

                   age    income  num.vehicles
age           1.000000  0.027429     -0.063666
income        0.027429  1.000000      0.139198
num.vehicles -0.063666  0.139198      1.000000

In [6]:
df["age"].describe()

count    1000.000000
mean       51.699815
std        18.863433
min         0.000000
25%        38.000000
50%        50.000000
75%        64.000000
max       146.680197
Name: age, dtype: float64

In [7]:
df[df["age"] > 100][["age", "income", "num.vehicles"]]

            age  income  num.vehicles
212  137.700030   60000           2.0
266  123.061023   12000           1.0
286  136.052160   31200           2.0
593  146.680197   40000           1.0
625  124.845087  175200           3.0
752  130.401605  200000           4.0
926  126.737284   43400           1.0
953  113.337207  255000           1.0

In [8]:
df[df["age"] < 18][["age", "income", "num.vehicles"]]

     age  income  num.vehicles
667  0.0   42400           2.0
868  0.0   48000           3.0
965  0.0  113950           2.0

In [9]:
df[df["income"] < 0][["age", "income", "num.vehicles"]]

      age  income  num.vehicles
691  60.0   -8700           3.0

In [10]:
(df["income"] < 0).sum()

np.int64(1)

In [11]:
clean_df = df[
    (df["age"] >= 18) &
    (df["age"] <= 100) &
    (df["income"] >= 0)
].copy()

In [12]:
clean_df.shape

(988, 11)

after_corr = clean_df[["age", "income", "num.vehicles"]].corr()

after_corr

I removed 11 rows from the age rows ,which is represnt imbosible age which is less than 18 and older than 100. in addtion i removed 1 row from the revenue row cause it is represent a negative number which is imposible too.

After cleaning the data,relation between age and income had almost no linear correlation (r = 0.009). relation between Age and number of vehicles also had a very weak negative correlation (r = -0.066), while relation between income and number of vehicles had a weak positive correlation (r = 0.138). Overall, the cleaned data does not show strong linear relationships among age, income, and number of vehicles.